### ISSUE TITLE
AVAudioSession problem

### ISSUE THREAD

**Issue by selcukca** [bluedesign/speech-recognition-feat-siri#7] opened 2017-01-27 15:08 UTC
Hi, 
sometimes i got the following error message:

[avas] AVAudioSession.mm:1074:-[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

Can you help me to solve this problem?

**Comment by bluedesign** [comment] 2017-01-29 08:33
hi, selcukalan
thanks your information.

I also confirmed that this error message appeared.
There is no problem with the code you write.
Probably I think the cause is the same as my issue #5 
Give me time to solve it.

**Comment by bluedesign** [comment] 2017-01-29 16:35
selcukalan, 
I tried presumption measures.
Please check if the same error message appears.

**Comment by bluedesign** [comment] 2017-02-04 05:46
### Notices

When used in conjunction with a plug-in that uses AVAudio Session like speech reading plug-in, the same message may be output by other plug-in,
I confirmed that error messages ceased to appear when only this plug-in was used.

### Development and verification environment

Xcode : 8.2.1(8C1002, swift compiler uses the latest version included in Xcode)
Node.js : v6.9.2
npm : 4.0.5
Apache Cordova : 6.5.0
cordova ios : 4.3.1

**Comment by bluedesign** [comment] 2017-03-22 07:42
This plug-in issues were resolved to close the Issue.

**Closed as completed by bluedesign** 2017-03-22 07:42 UTC
